# Example DDEV project configuration
# - You can as well use the interactive configurator:
#   https://mandrasch.github.io/ddev-pull-wp-generator/

# Local website will be available via <name>.ddev.site,
# e.g. for this config: https://my-wp-site.ddev.site
name: my-wp-site
type: wordpress
docroot: ""

# WebServer settings
php_version: "7.4"
mariadb_version: "10.3"
webserver_type: nginx-fpm

# Variables for the pull (provider) scripts
# - if you change these, run 'ddev restart'
web_environment:
# - if you don't use a child theme currently, just keep 'twentytwentyone-child'
- CHILD_THEME_FOLDER_NAME=twentytwentyone-child
# - if you don't want to use 'wp pull ssh', just keep the following values
- PRODUCTION_SSH_HOST=ssh-connect.example.org
- PRODUCTION_SSH_USER=sshUser123
- PRODUCTION_SSH_WP_DIR=/var/www/html/my-website.eu/

# All options: https://ddev.readthedocs.io/en/stable/users/extend/config_yaml/
